services:
    db:
        image: mysql:latest
        container_name: mysql-container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network
    php:
        build:
            context: ../docker
            dockerfile: php/Dockerfile
        container_name: php-container
        volumes:
            - ../project:/var/www/html
        networks:
            - app_network
    nginx:
        image: nginx:latest
        container_name: nginx-container
        volumes:
            - ../project:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "8080:80"
        networks:
            - app_network
    node:
        ports:
            - "3000:3000"
        environment:
            - DEBUG="http-proxy-middleware:*"
        build:
            context: ../frontend
            dockerfile: ../docker/node/Dockerfile
        container_name: node-container
        depends_on:
            -   nginx
        volumes:
            - ../frontend:/app
            - /app/node_modules
        networks:
            - app_network
volumes:
    db_data:

networks:
    app_network: